#.travis.yml
language: node_js
node_js:
  - "12.16.1"
branches:
only:
  - master
before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
script:
  - ng build --prod
after_success:
  - firebase deploy --token 1//0hjYxGNzKMPshCgYIARAAGBESNwF-L9IraoUcQZwlMxxew8ziUBkU7vR2vZ8a1eNF9KGnX4GRCdcdPYXelvbqel8HcZ_6KLofk6k
notifications:
  email:
  on_failure: change
  on_success: manuel.a.e.05@gmail.com
